locations:
  library:
    name: Central Library
    coordinates:
    - 23.213556
    - 72.686485
    - 0.0
    description: Central Library
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  jibaben:
    name: Jibaben
    coordinates:
    - 23.214793
    - 72.685498
    - 0.0
    description: Jibaben
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  jasubhai:
    name: Jasubhai
    coordinates:
    - 23.214685
    - 72.685762
    - 0.0
    description: Jasubhai
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  duven:
    name: Duven Hostel
    coordinates:
    - 23.210695
    - 72.685313
    - 0.0
    description: Duven Hostel
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  sports_complex:
    name: Sports Complex
    coordinates:
    - 23.211714
    - 72.687882
    - 0.0
    description: Sports Complex
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  guest_house:
    name: Guest House
    coordinates:
    - 23.211416
    - 72.689919
    - 0.0
    description: Guest House
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  jaiswal_mess:
    name: Jaiswal Mess
    coordinates:
    - 23.210932
    - 72.683778
    - 0.0
    description: Jaiswal Mess
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  new_pc:
    name: New PC
    coordinates:
    - 23.209977
    - 72.68441
    - 0.0
    description: New PC
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  rangmanch:
    name: Rangmanch
    coordinates:
    - 23.216262
    - 72.687482
    - 0.0
    description: Rangmanch
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
  gate_1:
    name: Gate 1
    coordinates:
    - 23.215753
    - 72.693079
    - 0.0
    description: Gate 1
    accessibility:
      wheelchair_accessible: true
      elevator_available: true
      audio_guidance: true
    estimated_time_from_center: 5
quick_tours:
  campus_highlights:
    name: Campus Highlights
    duration: 45
    locations:
    - library
    - jasubhai
    - sports_complex
    description: See the best of IIT Gandhinagar
